name: Deploy to Azure

on:
  push:
    branches:
      - main
      - terraform-flask-deployment

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: container-app-deploy

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Azure CLI
      uses: azure/CLI@v1
      with:
        inlineScript: |
          echo "Azure CLI setup complete"

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Build and push Docker image
      run: |
        az acr build --registry acaalbumsbtindol --image album-api .

    - name: Create container app environment
      run: |
        az containerapp env create --name env-album-containerapps --resource-group album-containerapps --location canadacentral

    - name: Deploy image to container app
      run: |
        az containerapp create --name album-api --resource-group album-containerapps --environment env-album-containerapps --image "acaalbumsbtindol.azurecr.io/album-api" --target-port 8080 --ingress external --registry-server "acaalbumsbtindol.azurecr.io"
